# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flomo < Formula
  desc "A Golang based command line interface of flomo. Visit https://easonyang.com to get more information."
  homepage "https://github.com/MrEasonYang/flomo-cli"
  version "1.0.2"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MrEasonYang/flomo-cli/releases/download/v1.0.2/flomo_1.0.2_macOS_x86_64.tar.gz"
      sha256 "160fbab6ee009f4ee7595f7701c76c5c0c0b0f12b633a9c265ae1d958e44df8e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/MrEasonYang/flomo-cli/releases/download/v1.0.2/flomo_1.0.2_macOS_arm64.tar.gz"
      sha256 "480f66afdac9d4db24efe1c3872c973787dc3ecc4eb01eaaf1b77f7b6775e144"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/MrEasonYang/flomo-cli/releases/download/v1.0.2/flomo_1.0.2_Linux_x86_64.tar.gz"
      sha256 "7205e054edbf5b16741c384b16b5a182e745907b64272dd877c421d457a7780c"
    end
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "flomo"
  end

  def caveats; <<~EOS
    Setup by using `flomo set api ${Your API}` command, send memo to flomo by using `flomo save ${Memo content}` command.
  EOS
  end
end
