# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flomo < Formula
  desc "A Golang based command line interface of flomo. Visit https://easonyang.com to get more information."
  homepage "https://github.com/MrEasonYang/flomo-cli"
  version "1.0.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MrEasonYang/flomo-cli/releases/download/v1.0.0/flomo_1.0.0_macOS_x86_64.tar.gz"
      sha256 "24a8eefcb95b61b2fc90b3919380b3a3e61251b0779428d1bef43359d472a1e8"
    end
    if Hardware::CPU.arm?
      url "https://github.com/MrEasonYang/flomo-cli/releases/download/v1.0.0/flomo_1.0.0_macOS_arm64.tar.gz"
      sha256 "2a25dc173b40f149c00a6f70fd9c9b949b67ca14f20c6acbde039a4cf86a440b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/MrEasonYang/flomo-cli/releases/download/v1.0.0/flomo_1.0.0_Linux_x86_64.tar.gz"
      sha256 "0f0f09352672b9d764bf7c407f96bf2fbf442083fad4394429e0e9ac4d3f1e6e"
    end
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "flomo"
  end

  def caveats; <<~EOS
    Setup by using `flomo set api ${Your API}` command, send memo to flomo by using `flomo save ${Memo content}` command.
  EOS
  end
end
